<?php
$h = static function ($value) { return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); };
$money = static function ($value) { return 'Rp ' . number_format((float) $value, 0, ',', '.'); };
$snapRequest = isset($snapshot['request']) && is_array($snapshot['request']) ? $snapshot['request'] : array();
$vendor = isset($snapshot['vendor']) && is_array($snapshot['vendor']) ? $snapshot['vendor'] : array();
$scopes = isset($snapshot['scope']) && is_array($snapshot['scope']) ? $snapshot['scope'] : array();
$materials = isset($snapshot['materials']) && is_array($snapshot['materials']) ? $snapshot['materials'] : array();
$field = static function ($key, $fallback = '') use ($snapRequest) { return isset($snapRequest[$key]) ? $snapRequest[$key] : $fallback; };
if (empty($request->nama_vendor) && isset($request->vendor_usulan)) { $request->nama_vendor = $request->vendor_usulan; }
?>
<style>
.pojasa-spk{font-family:Arial,sans-serif;color:#111;max-width:980px;margin:20px auto;padding:28px;border:1px solid #bbb;background:#fff}.pojasa-spk table{width:100%;border-collapse:collapse}.pojasa-spk th,.pojasa-spk td{border:1px solid #555;padding:6px;vertical-align:top}.pojasa-spk .no-border td{border:0;padding:2px 6px}.pojasa-spk .watermark{color:#b26a00;border:2px solid #b26a00;padding:7px;text-align:center;font-weight:bold;margin-bottom:16px}.pojasa-spk .signature td{height:100px;text-align:center;width:33%}@media print{.pojasa-spk{border:0;margin:0;max-width:none;padding:8px}.no-print{display:none!important}}
</style>
<section class="pojasa-spk">
  <div class="watermark">DRAFT KOMPATIBILITAS — BUKAN TEMPLATE RESMI PERUSAHAAN</div>
  <table class="no-border"><tr><td style="width:130px"><img src="<?= base_url('assets/images/logo1.png') ?>" alt="Logo" style="width:120px"></td><td><h2 style="margin:3px 0">PT. Karisma Indoagro Universal</h2><h3 style="margin:6px 0">SURAT PERINTAH KERJA (JASA)</h3></td></tr></table>
  <table class="no-border" style="margin:14px 0"><tr><td style="width:180px"><strong>Nomor SPK</strong></td><td>: <?= $h($spk->no_spk) ?></td><td style="width:150px"><strong>Tanggal Terbit</strong></td><td>: <?= $h(substr($spk->issued_at, 0, 10)) ?></td></tr><tr><td><strong>Nomor Request</strong></td><td>: <?= $h($spk->kd_po_jasa) ?></td><td><strong>Versi SPK</strong></td><td>: <?= (int) $spk->spk_version_no > 1 ? 'Rev. ' . ((int) $spk->spk_version_no - 1) : 'Versi awal' ?></td></tr></table>
  <h5>PIHAK PELAKSANA / VENDOR</h5>
  <table class="no-border"><tr><td style="width:180px">Nama</td><td>: <?= $h(isset($vendor['nama_vendor']) ? $vendor['nama_vendor'] : $request->nama_vendor) ?></td></tr><tr><td>Alamat</td><td>: <?= $h(isset($vendor['alamat_vendor']) ? $vendor['alamat_vendor'] : $request->alamat_vendor) ?></td></tr><tr><td>Kontak</td><td>: <?= $h(isset($vendor['nama_pic']) ? $vendor['nama_pic'] : $request->vendor_pic) ?> / <?= $h(isset($vendor['no_telpon']) ? $vendor['no_telpon'] : $request->vendor_phone) ?></td></tr><tr><td>Dasar pemilihan</td><td>: <?= $h($field('vendor_selection_reason', $request->vendor_selection_reason)) ?></td></tr></table>
  <h5>INFORMASI PEKERJAAN</h5>
  <table class="no-border"><tr><td style="width:180px">PIC / Departemen</td><td>: <?= $h($field('nm_user', $request->nm_user)) ?> / <?= $h($field('departemen', $request->departemen)) ?></td></tr><tr><td>Lokasi</td><td>: <?= $h($field('lokasi_pekerjaan', $request->lokasi_pekerjaan)) ?></td></tr><tr><td>Jadwal</td><td>: <?= $h($field('tgl_mulai_pekerjaan', $request->tgl_mulai_pekerjaan)) ?> s/d <?= $h($field('tgl_selesai_pekerjaan', $request->tgl_selesai_pekerjaan)) ?></td></tr><tr><td>Tujuan</td><td>: <?= nl2br($h($field('tujuan_pekerjaan', $request->tujuan_pekerjaan))) ?></td></tr></table>
  <h5>SCOPE PEKERJAAN</h5>
  <table><thead><tr><th style="width:45px">No</th><th>Uraian</th><th style="width:80px">Qty</th><th style="width:90px">Satuan</th><th style="width:145px">Estimasi</th></tr></thead><tbody><?php if (!$scopes) : ?><tr><td colspan="5" style="text-align:center">Tidak ada scope.</td></tr><?php endif; ?><?php foreach ($scopes as $index => $row) : ?><tr><td><?= $index + 1 ?></td><td><strong><?= $h($row['nama_scope']) ?></strong><br><?= nl2br($h($row['deskripsi'])) ?></td><td style="text-align:right"><?= $h($row['qty']) ?></td><td><?= $h($row['satuan']) ?></td><td style="text-align:right"><?= $money($row['total_estimasi']) ?></td></tr><?php endforeach; ?></tbody></table>
  <?php if ($materials) : ?><h5>MATERIAL / ALAT DAN BAHAN</h5><table><thead><tr><th style="width:45px">No</th><th>Material</th><th style="width:80px">Qty</th><th style="width:90px">Satuan</th><th style="width:120px">Sumber</th></tr></thead><tbody><?php foreach ($materials as $index => $row) : ?><tr><td><?= $index + 1 ?></td><td><?= $h($row['nama_material']) ?><br><?= nl2br($h($row['deskripsi'])) ?></td><td style="text-align:right"><?= $h($row['qty_kebutuhan']) ?></td><td><?= $h($row['satuan']) ?></td><td><?= $h($row['sumber_material']) ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?>
  <p style="margin-top:18px"><strong>Nilai estimasi pekerjaan:</strong> <?= $money($field('estimasi_total', $request->estimasi_total)) ?></p>
  <p>Pekerjaan wajib dilaksanakan sesuai scope, jadwal, standar keselamatan, dan ketentuan perusahaan yang berlaku. Ketentuan legal/komersial final menunggu template SPK resmi perusahaan.</p>
  <table class="signature" style="margin-top:30px"><tr><td>Yang Mengajukan,<br><br><br><br><u><?= $h($field('nm_user', $request->nm_user)) ?></u></td><td>Mengetahui,<br><br><br><br><u><?= $h($field('acc_with_kadep', $request->acc_with_kadep)) ?></u></td><td>Menyetujui,<br><br><br><br><u><?= $h($field('acc_with_direktur', $request->acc_with_direktur)) ?></u></td></tr></table>
</section>
