<script>
(function($) {
  'use strict';
  var requestCode = $('#p5RequestCode').val();
  var csrfToken = <?= json_encode($csrf_token) ?>;
  var canManage = <?= $can_manage ? 'true' : 'false' ?>;
  var currentState = <?= json_encode($purchasing_state) ?>;
  var canDeletePlanning = !!(currentState && currentState.can_delete_planning);
  var base = <?= json_encode(base_url('pojasa/ajax/purchasing/')) ?>;
  var documentBase = <?= json_encode(base_url('pojasa/workflow/document/')) ?>;
  var costVerifyUrl = <?= json_encode(base_url('pojasa/ajax/cost/verify')) ?>;
  var pickupPrepareUrl = <?= json_encode(base_url('pojasa/ajax/purchasing/pickup/prepare')) ?>;
  var searchTimer = null;

  renderState(currentState);
  if (currentState.pickup && currentState.pickup.pickup && currentState.pickup.pickup.status === 'MENUNGGU_PERSIAPAN_PURCHASING' && canManage) { $('#p5PickupPreparation').removeClass('d-none'); }
  $('#p5PickupReady').on('click',function(){post(pickupPrepareUrl,{kd_po_jasa:requestCode}).done(function(r){if(r.success){Swal.fire('Berhasil',r.message,'success');$('#p5PickupPreparation').addClass('d-none');}else{showError(r);}}).fail(ajaxError);});

  $('#p5AddComparison').on('click', function() {
    $('#p5ComparisonForm')[0].reset(); $('#p5VendorSourceType,#p5VendorSourceCode').val(''); $('#p5VendorSelected').text(''); $('#p5VendorResults').addClass('d-none').empty(); $('#p5ComparisonModal').modal('show');
  });

  $('#p5VendorSearch').on('input', function() {
    var query = $.trim($(this).val()); $('#p5VendorSourceType,#p5VendorSourceCode').val(''); $('#p5VendorSelected').text(''); if(query){$('#p5ManualVendorName').val('');}
    clearTimeout(searchTimer); searchTimer = setTimeout(function() { searchVendor(query); }, 250);
  });
  $('#p5StockSearch').on('input', function() {
    var query = $.trim($(this).val()); $('#p5StockId').val(''); $('#p5StockSelected').text('');
    clearTimeout(searchTimer); searchTimer = setTimeout(function() { searchStock(query); }, 250);
  });

  $('#p5ManualVendorName').on('input', function(){if($.trim($(this).val())){$('#p5VendorSearch,#p5VendorSourceType,#p5VendorSourceCode').val('');$('#p5VendorSelected').text('Vendor manual hanya disimpan pada penawaran ini.');$('#p5VendorResults').addClass('d-none').empty();}});

  $('#p5SaveComparison').on('click', function() {
    var form = new FormData($('#p5ComparisonForm')[0]); form.append('csrf_token', csrfToken);
    var button = $(this).prop('disabled', true);
    $.ajax({ url: base + 'comparison/save', method: 'POST', dataType: 'json', data: form, processData: false, contentType: false, headers: {'X-POJASA-CSRF': csrfToken} })
      .done(function(response) { if (!response.success) { showError(response); return; } updateFromResponse(response); $('#p5ComparisonModal').modal('hide'); Swal.fire('Tersimpan', response.message, 'success'); })
      .fail(ajaxError).always(function() { button.prop('disabled', false); });
  });

  $(document).on('click', '.p5-select-comparison', function() {
    var id = $(this).data('id');
    Swal.fire({ title: 'Pilih vendor ini?', input: 'textarea', inputPlaceholder: 'Alasan pemilihan vendor (wajib)', showCancelButton: true, confirmButtonText: 'Tetapkan vendor', preConfirm: function(value) { if (!$.trim(value)) { Swal.showValidationMessage('Alasan wajib diisi.'); return false; } return value; } })
      .then(function(result) { if (!result.value) { return; } post(base + 'comparison/select', {kd_po_jasa: requestCode, id_vendor_comparison: id, selection_reason: result.value}).done(handleMutation).fail(ajaxError); });
  });
  $(document).on('click', '.p5-delete-comparison', function() {
    var id = $(this).data('id'); Swal.fire({title:'Hapus penawaran?',text:'Dokumen penawaran akan diarsipkan.',icon:'warning',showCancelButton:true,confirmButtonText:'Ya, hapus'}).then(function(result) {
      if (!result.value) { return; } post(base + 'comparison/delete', {kd_po_jasa: requestCode, id_vendor_comparison: id}).done(handleMutation).fail(ajaxError);
    });
  });
  $(document).on('click', '.p5-open-stock', function() {
    $('#p5StockMaterialId').val($(this).data('id')); $('#p5StockMaterialName').text($(this).data('name')); $('#p5StockSearch,#p5StockId,#p5StockQty').val(''); $('#p5StockSelected').text(''); $('#p5StockResults').addClass('d-none').empty(); $('#p5StockModal').modal('show');
  });
  $('#p5AllocateStock').on('click', function() {
    var data = {kd_po_jasa:requestCode,id_material:$('#p5StockMaterialId').val(),id_brg_nk:$('#p5StockId').val(),qty:$('#p5StockQty').val(),idempotency_token:uuid()};
    if (!data.id_brg_nk || !(Number(data.qty)>0)) { Swal.fire('Data belum lengkap','Pilih barang dan isi quantity.','warning'); return; }
    Swal.fire({title:'Reservasi stok?',text:'Stok fisik belum akan dikurangi.',icon:'question',showCancelButton:true,confirmButtonText:'Ya, reservasi'}).then(function(result) {
      if (!result.value) { return; } post(base+'stock/allocate',data).done(function(response){ if(response.success){$('#p5StockModal').modal('hide');} handleMutation(response);}).fail(ajaxError);
    });
  });
  $(document).on('click', '.p5-release-stock', function() {
    var id=$(this).data('id'); Swal.fire({title:'Hapus reservasi?',input:'textarea',inputPlaceholder:'Alasan penghapusan (wajib)',showCancelButton:true,confirmButtonText:'Ya, hapus',confirmButtonColor:'#dc3545',preConfirm:function(v){if(!$.trim(v)){Swal.showValidationMessage('Alasan wajib diisi.');return false;}return v;}}).then(function(result){
      if(!result.value){return;} post(base+'stock/release',{kd_po_jasa:requestCode,id_allocation:id,reason:result.value,idempotency_token:uuid()}).done(handleMutation).fail(ajaxError);
    });
  });
  $(document).on('click', '.p5-open-draft', function() {
    var id=$(this).data('id'), material=findMaterial(id); $('#p5DraftMaterialId').val(id); $('#p5DraftMaterialName').text($(this).data('name')); $('#p5DraftQty').val(material&&material.draft&&material.draft.status_draft==='DRAFT' ? material.draft.qty : (material ? material.remaining_need : '')); $('#p5DraftPrice').val(material&&material.draft ? material.draft.harga_estimasi : (material ? material.harga_estimasi : 0)); $('#p5DraftNote').val(material&&material.draft ? material.draft.keterangan||'' : '');
    var select=$('#p5DraftVendor').html('<option value="">Belum ditentukan</option>'); (currentState.comparisons||[]).forEach(function(c){select.append($('<option>').val(c.id_vendor_jasa).text(c.vendor_name_snapshot).prop('selected',material&&material.draft&&Number(material.draft.id_vendor_jasa)===Number(c.id_vendor_jasa)));}); $('#p5DraftModal').modal('show');
  });
  $('#p5SaveDraft').on('click', function(){
    var data={kd_po_jasa:requestCode,id_material:$('#p5DraftMaterialId').val(),qty:$('#p5DraftQty').val(),harga_estimasi:$('#p5DraftPrice').val(),id_vendor_jasa:$('#p5DraftVendor').val(),keterangan:$('#p5DraftNote').val(),idempotency_token:uuid()};
    Swal.fire({title:'Buat draft pembelian?',text:'Draft tetap menyimpan referensi material request asal.',icon:'question',showCancelButton:true,confirmButtonText:'Ya, buat'}).then(function(result){if(!result.value){return;}post(base+'draft/save',data).done(function(response){if(response.success){$('#p5DraftModal').modal('hide');}handleMutation(response);}).fail(ajaxError);});
  });
  $(document).on('click','.p5-cancel-draft',function(){var id=$(this).data('id');Swal.fire({title:'Hapus draft pembelian?',input:'textarea',inputPlaceholder:'Alasan penghapusan',showCancelButton:true,confirmButtonText:'Ya, hapus',confirmButtonColor:'#dc3545',preConfirm:function(v){if(!$.trim(v)){Swal.showValidationMessage('Alasan wajib diisi.');return false;}return v;}}).then(function(result){if(!result.value){return;}post(base+'draft/cancel',{kd_po_jasa:requestCode,id_draft_pembelian:id,reason:result.value}).done(handleMutation).fail(ajaxError);});});

  $('#p5SubmitSpkRevision').on('click',function(){var request=currentState.request||{};$('#p5RevisionStart').val(request.tgl_mulai_pekerjaan||'');$('#p5RevisionEnd').val(request.tgl_selesai_pekerjaan||'');$('#p5RevisionReason').val('');$('#p5SpkRevisionModal').modal('show');});
  $('#p5SendSpkRevision').on('click',function(){var data={kd_po_jasa:requestCode,new_start_date:$('#p5RevisionStart').val(),new_end_date:$('#p5RevisionEnd').val(),reason:$.trim($('#p5RevisionReason').val()),idempotency_token:uuid()};if(!data.new_start_date||!data.new_end_date||!data.reason){Swal.fire('Data belum lengkap','Tanggal dan alasan revisi wajib diisi.','warning');return;}Swal.fire({title:'Ajukan Revisi SPK?',text:'Jadwal aktif tidak berubah sebelum ACC Direktur.',icon:'question',showCancelButton:true,confirmButtonText:'Ya, ajukan'}).then(function(result){if(!result.value){return;}post(base+'spk-revision/submit',data).done(function(response){if(response.success){$('#p5SpkRevisionModal').modal('hide');}handleMutation(response);}).fail(ajaxError);});});
  $(document).on('click','.p5-spk-decision',function(){var id=$(this).data('id'),action=$(this).data('action');var needsNote=action!=='ACC';Swal.fire({title:action+' Revisi SPK?',input:'textarea',inputPlaceholder:needsNote?'Catatan wajib':'Catatan keputusan (opsional)',icon:action==='REJECT'?'warning':'question',showCancelButton:true,confirmButtonText:'Ya, proses',preConfirm:function(v){if(needsNote&&!$.trim(v)){Swal.showValidationMessage('Catatan wajib diisi.');return false;}return v||'';}}).then(function(result){if(result.dismiss){return;}post(base+'spk-revision/decision',{kd_po_jasa:requestCode,id_spk_revision:id,action:action,note:result.value||'',idempotency_token:uuid()}).done(handleMutation).fail(ajaxError);});});

  $('#p8SubmitPurchase').on('click',function(){Swal.fire({title:'Ajukan semua draft aktif?',text:'Satu PO Pembelian berstatus PROSES PEMBELIAN akan dibuat. Draft yang terkirim dikunci.',icon:'question',showCancelButton:true,confirmButtonText:'Ya, ajukan'}).then(function(result){if(!result.value){return;}post(base+'purchase/submit',{kd_po_jasa:requestCode,idempotency_token:uuid()}).done(handleMutation).fail(ajaxError);});});
  $(document).on('click','#p8DeletePurchase',function(){Swal.fire({title:'Hapus PO Pembelian?',html:'PO dan seluruh detailnya akan dihapus. Draft material dikembalikan agar dapat diperbaiki atau diajukan ulang.',input:'textarea',inputPlaceholder:'Alasan penghapusan (wajib)',icon:'warning',showCancelButton:true,confirmButtonText:'Ya, hapus PO',confirmButtonColor:'#dc3545',preConfirm:function(v){if(!$.trim(v)){Swal.showValidationMessage('Alasan wajib diisi.');return false;}return v;}}).then(function(result){if(!result.value){return;}post(base+'purchase/delete',{kd_po_jasa:requestCode,reason:result.value}).done(handleMutation).fail(ajaxError);});});
  $(document).on('click','.p8-open-receipt',function(){var detail=$(this).data('detail'),remaining=$(this).data('remaining');$('#p8ReceiptDetailId').val(detail);$('#p8ReceiptMaterial').text($(this).data('name'));$('#p8ReceiptQty').val(remaining);$('#p8ReceiptPrice').val($(this).data('price')||0);$('#p8ReceiptDate').val(new Date().toISOString().slice(0,10));$('#p8ReceiptDocument').val('');$('#p8ReceiptModal').modal('show');});
  $('#p8SaveReceipt').on('click',function(){var data={kd_po_jasa:requestCode,id_detail_po_nk:$('#p8ReceiptDetailId').val(),qty_received:$('#p8ReceiptQty').val(),unit_price_actual:$('#p8ReceiptPrice').val(),on_hand_date:$('#p8ReceiptDate').val(),document_reference:$('#p8ReceiptDocument').val(),idempotency_token:uuid()};if(!(Number(data.qty_received)>0)||Number(data.unit_price_actual)<0||!data.on_hand_date){Swal.fire('Data belum lengkap','Isi quantity, harga aktual, dan tanggal ON_HAND.','warning');return;}post(base+'purchase/receive',data).done(function(response){if(response.success){$('#p8ReceiptModal').modal('hide');}handleMutation(response);}).fail(ajaxError);});
  $(document).on('click','.p8-reverse-receipt',function(){var id=$(this).data('id');Swal.fire({title:'Reversal penerimaan?',input:'textarea',inputPlaceholder:'Alasan reversal wajib',icon:'warning',showCancelButton:true,confirmButtonText:'Ya, reversal',preConfirm:function(v){if(!$.trim(v)){Swal.showValidationMessage('Alasan wajib diisi.');return false;}return v;}}).then(function(result){if(!result.value){return;}post(base+'purchase/reverse',{kd_po_jasa:requestCode,id_purchase_receipt:id,reason:result.value,idempotency_token:uuid()}).done(handleMutation).fail(ajaxError);});});
  $(document).on('click','.p8-cost-verify',function(){var id=$(this).data('id'),status=$(this).data('status');Swal.fire({title:status==='DIVERIFIKASI'?'Verifikasi biaya?':'Minta perbaikan biaya?',input:'textarea',inputPlaceholder:status==='DIVERIFIKASI'?'Catatan opsional':'Catatan perbaikan wajib',showCancelButton:true,confirmButtonText:'Simpan',preConfirm:function(v){if(status!=='DIVERIFIKASI'&&!$.trim(v)){Swal.showValidationMessage('Catatan wajib diisi.');return false;}return v||'';}}).then(function(result){if(result.dismiss){return;}post(costVerifyUrl,{kd_po_jasa:requestCode,id_biaya_aktual:id,verification_status:status,note:result.value||'',idempotency_token:uuid()}).done(function(response){if(!response.success){showError(response);return;}updateCsrf(response);refreshState(response.message);}).fail(ajaxError);});});

  $('#p8OpenDataChange').on('click',function(){openChange('DATA');}); $('#p8OpenCostChange').on('click',function(){openChange('COST');});
  $('#p8SubmitChange').on('click',function(){var type=$('#p8ChangeType').val(),payload={};if(type==='DATA'){payload.tgl_mulai_pekerjaan=$('#p8ChangeStart').val();payload.tgl_selesai_pekerjaan=$('#p8ChangeEnd').val();payload.scopes=[];payload.materials=[];$('#p8ChangeItems [data-kind="scope"]').each(function(){payload.scopes.push(changeRow($(this)));});$('#p8ChangeItems [data-kind="material"]').each(function(){payload.materials.push(changeRow($(this)));});}else{payload.approved_total=$('#p8ApprovedTotal').val();payload.cost_ids=[];$('#p8PendingCosts input:checked').each(function(){payload.cost_ids.push(Number($(this).val()));});}var reason=$.trim($('#p8ChangeReason').val());if(!reason){Swal.fire('Alasan wajib','Isi alasan perubahan SPK.','warning');return;}post(base+'change/submit',{kd_po_jasa:requestCode,change_type:type,payload:JSON.stringify(payload),reason:reason,idempotency_token:uuid()}).done(function(response){if(response.success){$('#p8ChangeModal').modal('hide');}handleMutation(response);}).fail(ajaxError);});
  $(document).on('click','.p8-change-decision',function(){var id=$(this).data('id'),action=$(this).data('action');Swal.fire({title:action+' perubahan SPK?',input:'textarea',inputPlaceholder:action==='ACC'?'Catatan opsional':'Catatan wajib',showCancelButton:true,confirmButtonText:'Proses',preConfirm:function(v){if(action!=='ACC'&&!$.trim(v)){Swal.showValidationMessage('Catatan wajib diisi.');return false;}return v||'';}}).then(function(result){if(result.dismiss){return;}post(base+'change/decide',{kd_po_jasa:requestCode,id_spk_change:id,action:action,note:result.value||'',idempotency_token:uuid()}).done(handleMutation).fail(ajaxError);});});

  function searchVendor(query) {
    $.getJSON(base+'vendors',{q:query}).done(function(response){if(!response.success){showError(response);return;}updateCsrf(response);var box=$('#p5VendorResults').empty();(response.data.items||[]).forEach(function(item){$('<button type="button" class="list-group-item list-group-item-action">').append($('<strong>').text(item.text),$('<small class="d-block text-muted">').text(item.subtitle||'')).data('item',item).on('click',function(){var selected=$(this).data('item');$('#p5ManualVendorName').val('');$('#p5VendorSearch').val(selected.text);$('#p5VendorSourceType').val(selected.source_type);$('#p5VendorSourceCode').val(selected.source_code);$('#p5VendorSelected').text('Dipilih: '+selected.text);box.addClass('d-none');}).appendTo(box);});box.toggleClass('d-none',!response.data.items.length);}).fail(ajaxError);
  }
  function searchStock(query) {
    $.getJSON(base+'stocks',{q:query}).done(function(response){if(!response.success){showError(response);return;}updateCsrf(response);var box=$('#p5StockResults').empty();(response.data.items||[]).forEach(function(item){var label=item.nama_barang+' · tersedia '+formatQty(item.available_stock)+' '+item.satuan;$('<button type="button" class="list-group-item list-group-item-action">').append($('<strong>').text(item.nama_barang),$('<small class="d-block text-muted">').text(item.kode_barangs+' | fisik '+formatQty(item.physical_stock)+' | reservasi '+formatQty(item.active_reservation)+' | tersedia '+formatQty(item.available_stock))).data('item',item).on('click',function(){var selected=$(this).data('item');$('#p5StockSearch').val(selected.nama_barang);$('#p5StockId').val(selected.id_brg_nk);$('#p5StockSelected').text(label);box.addClass('d-none');}).appendTo(box);});box.toggleClass('d-none',!response.data.items.length);}).fail(ajaxError);
  }
  function renderState(state) {
    currentState=state||{}; renderComparisons(currentState.comparisons||[]); renderMaterials(currentState.materials||[]); renderSpkRevisions(currentState); renderPurchase(currentState.purchase_integration||{}); renderChanges(currentState.spk_changes||{});
    renderExecution(currentState.execution||{});
    if(currentState.request){$('#p5Status').text(currentState.request.status);canManage=!!currentState.can_manage;canDeletePlanning=!!currentState.can_delete_planning;}
    var spk=currentState.spk;if(spk){$('#p5SpkCard').removeClass('d-none');$('#p5SpkNumber').text(spk.no_spk);$('#p5SpkVersion').text(Number(spk.spk_version_no||1)>1?'Rev. '+(Number(spk.spk_version_no)-1):'Versi awal');var urls=currentState.spk_urls||{view:<?= json_encode(base_url('pojasa/spk/' . rawurlencode($request->kd_po_jasa))) ?>,print:<?= json_encode(base_url('pojasa/spk/' . rawurlencode($request->kd_po_jasa) . '/print')) ?>,download:<?= json_encode(base_url('pojasa/spk/' . rawurlencode($request->kd_po_jasa) . '/download')) ?>};$('#p5SpkView').attr('href',urls.view);$('#p5SpkPrint').attr('href',urls.print);$('#p5SpkDownload').attr('href',urls.download);}else{$('#p5SpkCard').addClass('d-none');}
  }
  function renderSpkRevisions(state){var spk=state.spk;if(!spk){$('#p5SpkRevisionCard').addClass('d-none');return;}$('#p5SpkRevisionCard').removeClass('d-none');var rows=state.spk_revisions||[],pending=rows.some(function(r){return r.status==='MENUNGGU';}),returnRevision=rows.length&&rows[0].status==='REVISI';$('#p5SubmitSpkRevision').toggleClass('d-none',!state.can_submit_spk_revision||pending).html(returnRevision?'<i class="fas fa-edit mr-1"></i>Perbaiki & Ajukan Ulang':'<i class="fas fa-edit mr-1"></i>Ajukan Revisi SPK');$('#p5SpkRevisionSummary').html('<strong>'+esc(spk.no_spk)+'</strong> · '+(Number(spk.spk_version_no||1)>1?'Rev. '+(Number(spk.spk_version_no)-1):'Versi awal'));var body=$('#p5SpkRevisionBody').empty();if(!rows.length){body.html('<tr><td colspan="7" class="text-center text-muted">Belum ada Revisi SPK.</td></tr>');}rows.forEach(function(r){var actions='';if(state.can_approve_spk_revision&&r.status==='MENUNGGU'){actions='<button class="btn btn-xs btn-success p5-spk-decision" data-id="'+Number(r.id_spk_revision)+'" data-action="ACC">ACC</button> <button class="btn btn-xs btn-warning p5-spk-decision" data-id="'+Number(r.id_spk_revision)+'" data-action="REVISI">REVISI</button> <button class="btn btn-xs btn-danger p5-spk-decision" data-id="'+Number(r.id_spk_revision)+'" data-action="REJECT">REJECT</button>';}body.append('<tr><td>'+esc(r.requested_at)+'<br><small>'+esc(r.requested_name)+'</small></td><td>'+Number(r.from_version_no)+'</td><td>'+esc(r.old_start_date)+' s/d '+esc(r.old_end_date)+'</td><td>'+esc(r.new_start_date)+' s/d '+esc(r.new_end_date)+'</td><td>'+esc(r.reason)+(r.decision_note?'<br><small>Catatan: '+esc(r.decision_note)+'</small>':'')+'</td><td>'+esc(r.status)+'</td><td>'+actions+'</td></tr>');});var archives=$('#p5SpkArchiveList').empty();(state.spk_archives||[]).forEach(function(a){archives.append('<a class="btn btn-outline-secondary btn-sm mr-2 mb-2" href="<?= base_url('pojasa/spk/' . rawurlencode($request->kd_po_jasa) . '/version/') ?>'+Number(a.spk_version_no)+'">Versi '+Number(a.spk_version_no)+'</a>');});if(!archives.children().length){archives.html('<span class="text-muted">Belum ada versi terdahulu.</span>');}}
  function renderExecution(execution) {
    var summary=execution.cost_summary||{};['requested','approved','actual','variance'].forEach(function(key){$('#p5ExecutionSummary [data-key="'+key+'"]').text(money(summary[key]||0));});
    var progress=(execution.progress||[]).map(function(row){return '<tr><td>'+esc(row.tgl_progress)+'</td><td>'+esc(row.aktivitas||row.milestone||'-')+'</td><td>'+formatQty(row.progress_persen)+'%</td><td>'+esc(row.status_progress)+'</td><td>'+esc(row.kendala||'-')+' / '+esc(row.tindak_lanjut||'-')+'</td></tr>';}).join('');
    $('#p5ProgressBody').html(progress||'<tr><td colspan="5" class="text-center text-muted">Belum ada progress.</td></tr>');
    var receipts=(execution.receipts||[]).map(function(row){return '<tr><td>'+esc(row.receipt_at)+'</td><td>'+esc(row.no_receipt)+'</td><td>'+esc(row.nama_material)+'</td><td>'+formatQty(row.qty_received)+' '+esc(row.satuan)+'</td><td>'+Number(row.id_transnk)+'</td></tr>';}).join('');
    $('#p5ReceiptBody').html(receipts||'<tr><td colspan="5" class="text-center text-muted">Belum ada penerimaan.</td></tr>');
    var costs=(execution.costs||[]).map(function(row){var evidence=row.id_dokumen_bukti?'<a href="'+documentBase+Number(row.id_dokumen_bukti)+'/download">'+esc(row.file_original||'Unduh')+'</a>':esc(row.source_document_reference||row.source_po_nk_code||'-');var verify=row.record_type==='MANUAL'?'<button class="btn btn-xs btn-success p8-cost-verify" data-id="'+Number(row.id_biaya_aktual)+'" data-status="DIVERIFIKASI">Verifikasi</button> <button class="btn btn-xs btn-warning p8-cost-verify" data-id="'+Number(row.id_biaya_aktual)+'" data-status="PERLU_PERBAIKAN">Perbaikan</button>':'Otomatis';return '<tr><td>'+esc(row.tgl_biaya)+'</td><td>'+esc(row.source_type||row.cost_source)+'</td><td>'+esc(row.jenis_biaya)+'</td><td>'+money(row.nominal)+'</td><td>'+evidence+'</td><td>'+esc(row.record_status||'-')+'<br><small>'+esc(row.verification_status||'-')+'</small></td><td>'+verify+'</td></tr>';}).join('');
    $('#p5CostBody').html(costs||'<tr><td colspan="7" class="text-center text-muted">Belum ada biaya aktual.</td></tr>');
  }
  function renderPurchase(state){var submission=state.submission,details=state.details||[],receipts=state.receipts||[];$('#p8SubmitPurchase').toggleClass('d-none',!(currentState.can_manage&&currentState.spk));var summary=submission?'<strong>'+esc(submission.kd_po_nk)+'</strong> · '+esc(submission.status)+' · SPK '+esc(submission.no_spk)+' versi '+Number(submission.spk_version_no):'Belum ada PO Pembelian terhubung.';if(submission&&currentState.can_delete_purchase){summary+=' <button id="p8DeletePurchase" type="button" class="btn btn-xs btn-outline-danger float-right"><i class="fas fa-trash mr-1"></i>Hapus PO</button><small class="d-block mt-2 text-muted">Hanya tersedia sebelum ada penerimaan atau penyesuaian PO.</small>';}$('#p8PurchaseSummary').html(summary);var body=$('#p8PurchaseBody').empty();if(!details.length){body.html('<tr><td colspan="7" class="text-center text-muted">Belum ada detail PO Pembelian.</td></tr>');}details.forEach(function(d){var remaining=Math.max(0,Number(d.qty_submitted)-Number(d.qty_received)),action=remaining>0&&currentState.can_delete_planning?'<button class="btn btn-xs btn-success p8-open-receipt" data-detail="'+Number(d.id_detail_po_nk)+'" data-remaining="'+remaining+'" data-price="'+Number(d.estimated_unit_price)+'" data-name="'+attr(d.nama_material)+'">Terima</button>':'';body.append('<tr><td>'+esc(d.nama_material)+'</td><td>'+formatQty(d.qty_submitted)+' '+esc(d.satuan)+'</td><td>'+formatQty(d.qty_received)+'</td><td>'+formatQty(remaining)+'</td><td>'+money(d.total_nyata)+'</td><td>'+esc(d.fulfillment_status)+'</td><td>'+action+'</td></tr>');});var receiptBody=$('#p8ReceiptBody').empty();if(!receipts.length){receiptBody.html('<tr><td colspan="6" class="text-center text-muted">Belum ada penerimaan.</td></tr>');}var reversed={};receipts.forEach(function(r){if(r.reversal_of_id){reversed[Number(r.id_purchase_receipt)] = true;}});receipts.forEach(function(r){var action=r.record_type==='RECEIPT'&&!reversed[Number(r.id_purchase_receipt)]&&currentState.can_delete_planning?'<button class="btn btn-xs btn-outline-danger p8-reverse-receipt" data-id="'+Number(r.id_purchase_receipt)+'">Reversal</button>':'';receiptBody.append('<tr><td>'+esc(r.on_hand_date)+'</td><td>'+esc(r.receipt_reference)+'</td><td>'+formatQty(r.qty_received)+'</td><td>'+money(r.total_actual)+'</td><td>'+esc(r.record_type)+'</td><td>'+action+'</td></tr>');});}
  function renderChanges(state){$('#p8ChangeCard').toggleClass('d-none',!state.ready);$('#p8OpenDataChange').toggleClass('d-none',!state.can_submit);$('#p8OpenCostChange').toggleClass('d-none',!state.can_submit||!(state.pending_costs||[]).length);var body=$('#p8ChangeBody').empty(),changes=state.changes||[];if(!changes.length){body.html('<tr><td colspan="7" class="text-center text-muted">Belum ada perubahan pasca-SPK.</td></tr>');}changes.forEach(function(c){var actions='';if(state.can_decide&&((c.current_stage==='DIREKTUR_OPERASIONAL'&&c.status==='MENUNGGU_DIROPS')||(c.current_stage==='DIREKTUR'&&c.status==='MENUNGGU_DIREKTUR'))){actions=['ACC','REVISI','REJECT'].map(function(a){return '<button class="btn btn-xs btn-'+(a==='ACC'?'success':a==='REVISI'?'warning':'danger')+' p8-change-decision" data-id="'+Number(c.id_spk_change)+'" data-action="'+a+'">'+a+'</button>';}).join(' ');}body.append('<tr><td>'+esc(c.created_at)+'<br><small>'+esc(c.requested_name)+'</small></td><td>'+esc(c.change_type)+'</td><td>'+formatQty(c.quantity_impact)+'</td><td>'+money(c.cost_impact)+'</td><td>'+esc(c.status)+'<br><small>'+esc(c.current_stage)+'</small></td><td>'+esc(c.reason)+'</td><td>'+actions+'</td></tr>');});}
  function openChange(type){$('#p8ChangeType').val(type);$('#p8ChangeReason').val('');$('#p8DataChangeFields').toggleClass('d-none',type!=='DATA');$('#p8CostChangeFields').toggleClass('d-none',type!=='COST');$('#p8ChangeTitle').text(type==='DATA'?'Ajukan Revisi Data SPK':'Ajukan Revisi Biaya SPK');if(type==='DATA'){var req=currentState.request||{};$('#p8ChangeStart').val(req.tgl_mulai_pekerjaan||'');$('#p8ChangeEnd').val(req.tgl_selesai_pekerjaan||'');var wrap=$('#p8ChangeItems').empty();(currentState.scopes||[]).forEach(function(s){wrap.append(changeFields('scope',s.id_scope,s.nama_scope,s.deskripsi,s.qty,s.satuan,s.harga_estimasi));});(currentState.materials||[]).forEach(function(m){wrap.append(changeFields('material',m.id_material,m.nama_material,m.deskripsi,m.qty_kebutuhan,m.satuan,m.harga_estimasi));});}else{var sc=currentState.spk_changes||{},pending=sc.pending_costs||[],summary=currentState.execution&&currentState.execution.cost_summary?currentState.execution.cost_summary:{},actual=summary.actual||0;$('#p8ApprovedTotal').val(Math.max(Number(actual)||0,Number(summary.approved)||0));var list=$('#p8PendingCosts').empty();pending.forEach(function(c){list.append('<div class="custom-control custom-checkbox"><input type="checkbox" checked class="custom-control-input" id="p8cost'+Number(c.id_biaya_aktual)+'" value="'+Number(c.id_biaya_aktual)+'"><label class="custom-control-label" for="p8cost'+Number(c.id_biaya_aktual)+'">'+esc(c.jenis_biaya)+' · '+money(c.nominal)+'</label></div>');});}$('#p8ChangeModal').modal('show');}
  function changeFields(kind,id,name,description,qty,unit,price){return '<div class="border rounded p-2 mb-2" data-kind="'+kind+'" data-id="'+Number(id)+'"><strong>'+(kind==='scope'?'Scope':'Material')+'</strong><div class="row"><div class="col-md-3"><input class="form-control form-control-sm js-change-name" value="'+attr(name)+'" placeholder="Nama"></div><div class="col-md-3"><input class="form-control form-control-sm js-change-description" value="'+attr(description||'')+'" placeholder="Deskripsi"></div><div class="col-md-2"><input type="number" min="0.01" step="0.01" class="form-control form-control-sm js-change-qty" value="'+Number(qty)+'" placeholder="Qty"></div><div class="col-md-2"><input class="form-control form-control-sm js-change-unit" value="'+attr(unit)+'" placeholder="Satuan"></div><div class="col-md-2"><input type="number" min="0" step="0.01" class="form-control form-control-sm js-change-price" value="'+Number(price)+'" placeholder="Estimasi"></div></div></div>';}
  function changeRow(row){return{id:Number(row.data('id')),name:row.find('.js-change-name').val(),description:row.find('.js-change-description').val(),qty:row.find('.js-change-qty').val(),unit:row.find('.js-change-unit').val(),estimated_price:row.find('.js-change-price').val()};}
  function renderComparisons(rows) {
    var body=$('#p5ComparisonBody').empty();if(!rows.length){body.html('<tr><td colspan="7" class="text-center text-muted">Belum ada penawaran pembanding.</td></tr>');$('#p5SelectedReason').addClass('d-none');return;}
    var selected=null;rows.forEach(function(row){if(Number(row.is_selected)===1){selected=row;}var actions='';if(canManage){actions=Number(row.is_selected)===1?'<span class="text-success"><i class="fas fa-check-circle"></i></span>':'<button class="btn btn-xs btn-success p5-select-comparison" data-id="'+Number(row.id_vendor_comparison)+'">Pilih</button> <button class="btn btn-xs btn-danger p5-delete-comparison" data-id="'+Number(row.id_vendor_comparison)+'">Hapus</button>';}var doc=row.id_dokumen?'<a target="_blank" href="'+documentBase+Number(row.id_dokumen)+'">'+esc(row.file_original||'Dokumen')+'</a>':'-';body.append('<tr class="'+(Number(row.is_selected)===1?'table-success':'')+'"><td><strong>'+esc(row.vendor_name_snapshot)+'</strong><br><small>'+esc(row.vendor_type||'')+'</small></td><td>'+esc(row.quotation_no||'-')+'<br><small>'+esc(row.quotation_date||'-')+'</small></td><td class="text-right">'+money(row.amount)+'</td><td>'+esc(row.lead_time_days===null?'-':row.lead_time_days+' hari')+'</td><td>'+esc(row.offer_detail||'-')+'<br>'+doc+'</td><td>'+(Number(row.is_selected)===1?'<span class="badge badge-success">TERPILIH</span>':'<span class="badge badge-light">PEMBANDING</span>')+'</td><td>'+actions+'</td></tr>');});
    if(selected){$('#p5SelectedReason').removeClass('d-none').html('<strong>Alasan vendor terpilih:</strong> '+esc(selected.selection_reason||'-'));}else{$('#p5SelectedReason').addClass('d-none');}
  }
  function renderMaterials(rows) {
    var wrap=$('#p5MaterialList').empty();if(!rows.length){wrap.html('<div class="text-center text-muted py-3">Tidak ada material.</div>');return;}rows.forEach(function(m){var allocations='';(m.allocations||[]).forEach(function(a){var remaining=Math.max(0,Number(a.qty_allocation)-Number(a.qty_received)-Number(a.qty_released));allocations+='<tr><td>'+esc(a.nama_barang)+'</td><td>'+formatQty(a.qty_allocation)+'</td><td>'+formatQty(a.qty_received)+'</td><td>'+formatQty(remaining)+'</td><td><span class="badge badge-'+(a.status_allocation==='RELEASED'?'secondary':a.status_allocation==='RECEIVED'?'success':'warning')+'">'+esc(a.status_allocation)+'</span></td><td>'+(canDeletePlanning&&remaining>0?'<button class="btn btn-xs btn-outline-danger p5-release-stock" data-id="'+Number(a.id_allocation)+'">Hapus</button>':'')+'</td></tr>';});if(!allocations){allocations='<tr><td colspan="6" class="text-center text-muted">Belum ada reservasi.</td></tr>';}
      var draft=m.draft;var draftHtml=draft?'<div class="alert alert-'+(draft.status_draft==='DRAFT'?'primary':'secondary')+' py-2 mb-0">Draft #'+Number(draft.id_draft_pembelian)+' · '+formatQty(draft.qty)+' · '+money(Number(draft.qty)*Number(draft.harga_estimasi))+' · '+esc(draft.status_draft)+(canDeletePlanning&&draft.status_draft==='DRAFT'?' <button class="btn btn-xs btn-outline-danger float-right p5-cancel-draft" data-id="'+Number(draft.id_draft_pembelian)+'">Hapus</button>':'')+'</div>':'<span class="text-muted">Belum ada draft pembelian.</span>';
      var planningActions='';if(canManage&&Number(m.remaining_need)>0){planningActions+='<button class="btn btn-warning btn-sm p5-open-stock" data-id="'+Number(m.id_material)+'" data-name="'+attr(m.nama_material)+'"><i class="fas fa-box"></i> Alokasi</button> ';}if(canManage&&(Number(m.remaining_need)>0||(draft&&draft.status_draft==='DRAFT'))){planningActions+='<button class="btn btn-primary btn-sm p5-open-draft" data-id="'+Number(m.id_material)+'" data-name="'+attr(m.nama_material)+'"><i class="fas fa-shopping-cart"></i> '+(draft&&draft.status_draft==='DRAFT'?'Edit draft':'Draft beli')+'</button>';}wrap.append('<div class="card border mb-3"><div class="card-header bg-light"><div class="d-flex justify-content-between"><div><strong>'+Number(m.line_no)+'. '+esc(m.nama_material)+'</strong><br><small>Kebutuhan '+formatQty(m.qty_kebutuhan)+' '+esc(m.satuan||'')+' · reservasi aktif '+formatQty(m.reserved_qty)+' · draft aktif '+formatQty(m.active_draft_qty)+' · sisa '+formatQty(m.remaining_need)+'</small></div><div>'+planningActions+'</div></div></div><div class="card-body p-2"><div class="table-responsive"><table class="table table-sm table-bordered mb-2"><thead><tr><th>Barang stok</th><th>Alokasi</th><th>Diterima</th><th>Sisa reservasi</th><th>Status</th><th>Aksi</th></tr></thead><tbody>'+allocations+'</tbody></table></div>'+draftHtml+'</div></div>');});
  }
  function findMaterial(id){var found=null;(currentState.materials||[]).forEach(function(m){if(Number(m.id_material)===Number(id)){found=m;}});return found;}
  function post(url,data){data=data||{};data.csrf_token=csrfToken;return $.ajax({url:url,method:'POST',dataType:'json',headers:{'X-POJASA-CSRF':csrfToken},data:data});}
  function handleMutation(response){if(!response.success){showError(response);return;}updateFromResponse(response);Swal.fire({title:'Berhasil',text:response.message,icon:'success',timer:1700,showConfirmButton:false});$(document).trigger('pojasa:refresh-notifications');}
  function updateFromResponse(response){updateCsrf(response);renderState(response.data);}
  function refreshState(message){$.getJSON(base+'state/'+encodeURIComponent(requestCode)).done(function(response){if(!response.success){showError(response);return;}updateFromResponse(response);Swal.fire({title:'Berhasil',text:message||'Data diperbarui.',icon:'success',timer:1500,showConfirmButton:false});}).fail(ajaxError);}
  function updateCsrf(response){if(response&&response.data&&response.data.csrf_token){csrfToken=response.data.csrf_token;}}
  function showError(response){var errors=response.errors||{};var list=Object.keys(errors).map(function(k){return esc(errors[k]);});Swal.fire({title:'Aksi gagal',html:list.length?list.join('<br>'):esc(response.message||'Aksi tidak dapat diproses.'),icon:response.code==='VALIDATION_ERROR'?'warning':'error'});}
  function ajaxError(xhr){if(xhr.status===401&&xhr.responseJSON&&xhr.responseJSON.redirect){window.location.href=xhr.responseJSON.redirect;return;}showError(xhr.responseJSON||{message:'Koneksi ke server gagal.'});}
  function money(v){return 'Rp '+Math.round(Number(v)||0).toLocaleString('id-ID');} function formatQty(v){return (Number(v)||0).toLocaleString('id-ID',{maximumFractionDigits:2});} function esc(v){return $('<div>').text(v===null||v===undefined?'':v).html();} function attr(v){return esc(v).replace(/"/g,'&quot;');}
  function uuid(){if(window.crypto&&window.crypto.getRandomValues){var b=new Uint8Array(16);window.crypto.getRandomValues(b);b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;return Array.prototype.map.call(b,function(x,i){return(i===4||i===6||i===8||i===10?'-':'')+('0'+x.toString(16)).slice(-2);}).join('');}return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16);});}
})(jQuery);
</script>
